## Imports

In [3]:
import pandas as pd
import numpy as np

# Python

### Variable Assignment

In [4]:
a = 5
b = 2

c = a*b ## Multiplizieren

print(c)

10


In [13]:
b = b**2 ## Potenzieren

In [15]:
b = b / 2 ## Dividieren 
b

2.0

In [16]:
## Conversion
str(b)

'2.0'

In [17]:
d = 5
d%2 ## Modulo

1

### Types

In [5]:
a = True
b = 2
c = "string"
d = 2.0

In [12]:
type(d)

float

### Strings

In [18]:
text = "abcdefg"
text.upper()

'ABCDEFG'

In [19]:
text.replace("b","B")

'aBcdefg'

In [21]:
text += "h"
text

'abcdefgh'

### Lists

In [22]:
new_list = [1,2,3,5,7] # Can only contain variables of the same type
new_list.append(5)
new_list

[1, 2, 3, 5, 7, 5]

In [23]:
another_list = [4,5]
new_list = new_list+another_list
new_list

[1, 2, 3, 5, 7, 5, 4, 5]

In [24]:
new_list.index(5) #Index of first occurence

3

In [25]:
new_list[0:3] #letzte Stelle ist immer exklusiv

[1, 2, 3]

In [26]:
new_list[-1]

5

In [29]:
new_list[-3:]

[5, 4, 5]

In [30]:
new_list[:-3]

[1, 2, 3, 5, 7]

### Dictionaries

In [32]:
my_dict = {"random_text":["lalal","das ist ein Text","mega nice"],
          "random_number":[1,5,7]}

In [33]:
my_dict["random_text"]

['lalal', 'das ist ein Text', 'mega nice']

In [34]:
my_dict["random_number"]

[1, 5, 7]

In [38]:
for k,v in my_dict.items():
    print(f"{k}: {v}")

random_text: ['lalal', 'das ist ein Text', 'mega nice']
random_number: [1, 5, 7]


In [39]:
for k in my_dict:
    print(k)

random_text
random_number


# Numpy

### Numpy Arrays

In [40]:
new_array = np.array(new_list)

In [41]:
new_array[0:5] ## Index 0-4 wird ausgegeben

array([1, 2, 3, 5, 7])

In [42]:
new_array == 5 ## Masking

array([False, False, False,  True, False,  True, False,  True])

In [43]:
new_array[new_array==5] ## Anwenden der Maske

array([5, 5, 5])

In [44]:
new_array

array([1, 2, 3, 5, 7, 5, 4, 5])

In [45]:
new_array + 5 ## Mit Numpy-Arrays sind Rechenoperationen direkt anwendbar

array([ 6,  7,  8, 10, 12, 10,  9, 10])

In [46]:
new_array.shape

(8,)

In [50]:
more_dimensional_array = np.zeros(shape=(3,2))

In [53]:
more_dimensional_array[0,0] = 1 ## [row,column]
more_dimensional_array

array([[1., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
more_dimensional_array[1,0] = 2
more_dimensional_array

array([[1., 0.],
       [2., 0.],
       [0., 0.]])

In [56]:
more_dimensional_array.shape

(3, 2)

In [59]:
more_dimensional_array = more_dimensional_array * 2
more_dimensional_array

array([[2., 0.],
       [4., 0.],
       [0., 0.]])

In [65]:
np.vstack((more_dimensional_array,[2,5])) 

array([[2., 0.],
       [4., 0.],
       [0., 0.],
       [2., 5.]])

# Pandas

### Pandas Dataframe

In [66]:
## Anlegen eines Pandas-Dataframes
df = pd.DataFrame(my_dict)

In [67]:
df ## Ein DataFrame kann unterschiedliche Typen enthalten

random_text  random_number
0             lalal              1
1  das ist ein Text              5
2         mega nice              7

### Pandas Series

In [69]:
type(df.random_text)

pandas.core.series.Series

In [70]:
df.random_text

0               lalal
1    das ist ein Text
2           mega nice
Name: random_text, dtype: object

In [71]:
type(df)

pandas.core.frame.DataFrame

### Indexing

In [72]:
### iloc
df.iloc[0:2,[0]] ##[row,column]

random_text
0             lalal
1  das ist ein Text

In [73]:
### loc
df.loc[:,["random_text"]]

random_text
0             lalal
1  das ist ein Text
2         mega nice

In [74]:
### filter
df.loc[df.random_text == "lalal",['random_text']]

random_text
0       lalal

### nützliche Funktionen

In [77]:
### head
df.head()

random_text  random_number
0             lalal              1
1  das ist ein Text              5
2         mega nice              7

In [78]:
df.head(2)

random_text  random_number
0             lalal              1
1  das ist ein Text              5

In [79]:
### info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   random_text    3 non-null      object
 1   random_number  3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


In [80]:
### Funktionen anwenden
df['new_string']  = df.random_text.apply(lambda x: x.upper())

In [81]:
df

random_text  random_number        new_string
0             lalal              1             LALAL
1  das ist ein Text              5  DAS IST EIN TEXT
2         mega nice              7         MEGA NICE